### PR TITLE
Make it easier to select tags

### LINKED ISSUE #73: Copying tag ID is hard
When I go to add a photo, I want to copy the tag ID easily so I can paste it into Flickr.

At the moment, it is hard to accurately select the ID. Because it is text, if I double-click it, it only selects part of the tag. If I triple-click, the whole line is selected. 

select

I suggest changing the output to:

`<input type="text" readonly value="openplaques:id=42552">`

This renders as:

readonly

Easier to copy and it is still visually distinct.

### PR DESCRIPTION
**Pull request by edent**
Fixes #73

### CODE REVIEW

**Comment by jnicho02** [comment]
aha! I wanted to know how to do that. Did you notice/use the copy-to-clipboard buttons?

**Comment by edent** [comment]
I don't see any copy-to-clipboard button.  Or am I being a bit thick...?

copy

**Comment by jnicho02** [comment]
screen shot 2017-03-15 at 11 57 02 am
Oops, I meant on the plaque page itself.

I think that both methods would be useful. I will extend your PR

**Comment by jnicho02** [comment]
i've not tried editing someone else's pull request before...not sure whether my changes are being added

**Pull request merged**
